// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: modules/banking/interface/grpc/proto/account.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountServicesClient is the client API for AccountServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServicesClient interface {
	// Sends a greeting
	CreateAccountHandler(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
}

type accountServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServicesClient(cc grpc.ClientConnInterface) AccountServicesClient {
	return &accountServicesClient{cc}
}

func (c *accountServicesClient) CreateAccountHandler(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountServices/CreateAccountHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServicesServer is the server API for AccountServices service.
// All implementations must embed UnimplementedAccountServicesServer
// for forward compatibility
type AccountServicesServer interface {
	// Sends a greeting
	CreateAccountHandler(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	mustEmbedUnimplementedAccountServicesServer()
}

// UnimplementedAccountServicesServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServicesServer struct {
}

func (UnimplementedAccountServicesServer) CreateAccountHandler(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountHandler not implemented")
}
func (UnimplementedAccountServicesServer) mustEmbedUnimplementedAccountServicesServer() {}

// UnsafeAccountServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServicesServer will
// result in compilation errors.
type UnsafeAccountServicesServer interface {
	mustEmbedUnimplementedAccountServicesServer()
}

func RegisterAccountServicesServer(s grpc.ServiceRegistrar, srv AccountServicesServer) {
	s.RegisterService(&AccountServices_ServiceDesc, srv)
}

func _AccountServices_CreateAccountHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServicesServer).CreateAccountHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountServices/CreateAccountHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServicesServer).CreateAccountHandler(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountServices_ServiceDesc is the grpc.ServiceDesc for AccountServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountServices",
	HandlerType: (*AccountServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountHandler",
			Handler:    _AccountServices_CreateAccountHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/banking/interface/grpc/proto/account.proto",
}
